/**
 * Created by Jonathan Batista <jonathan.b.d.o.s@gmail.com> on 6/11/17.
 */

export const ITEMS_FETCHING = 'ITEMS_FETCHING';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const ITEMS_FETCH_FAIL = 'ITEMS_FETCH_FAIL';
export const ITEMS_CHANGE = 'ITEMS_CHANGE';
export const ITEM_SELECTED = 'ITEM_SELECTED';

export const INVENTORY_CHANGE = 'INVENTORY_CHANGE';
export const INVENTORY_RESETED = 'INVENTORY_RESETED';

export const STATISTICS_FETCHING = 'STATISTICS_FETCHING';
export const STATISTICS_FETCH_SUCCESS = 'STATISTICS_FETCH_SUCCESS';
export const STATISTICS_FETCH_FAIL = 'STATISTICS_FETCH_FAIL';

export const REGISTER_FORM_DONE = 'REGISTER_FORM_DONE';
export const REGISTER_FORM_CHANGED = 'REGISTER_FORM_CHANGED';
export const REGISTER_FORM_RESET = 'REGISTER_FORM_RESET';
export const REGISTER_FORM_SENDING = 'REGISTER_FORM_SENDING';
export const REGISTER_FORM_TOGGLE_ERRORS = 'REGISTER_FORM_TOGGLE_ERRORS';
export const REGISTER_FORM_CHANGE_ERRORS = 'REGISTER_FORM_CHANGE_ERRORS';

export const SURVIVOR_LOCATION_CHANGED = 'SURVIVOR_LOCATION_CHANGED';

export const SURVIVORS_FETCHING = 'SURVIVORS_FETCHING';
export const SURVIVORS_FETCH_SUCCESS = 'SURVIVORS_FETCH_SUCCESS';
export const SURVIVORS_FETCH_FAIL = 'SURVIVORS_FETCH_FAIL';
